# ======= UNITS ============
# Length:   m
# Mass:     kg
# Time:     s
# Force:    N
# Pressure: Pa
# Density:  kg/m3
# ==========================

[pfc]
# ==========================
# specify the main p3dat file path
main = ./PFC/main.p3dat
randomSeed = 10005
initPorosity = 0.2
recordEpsilonInterval = 0.001
compressRate = 0.01
# max strain in triaxial test, direction z, absolute number
maxStrain = 0.15
#==========================

# parameters of particle template
[clump]
#==========================
# shape of clump, no unit
# radius of ball 1
ball1 = 4
# radius of ball 2
ball2 = 3
# distance between the center of ball1 and ball2
distance = 4
# density of particle
density = 2920
damp = 0.7
# size of clumps, radius of equal-volume ball diameter
# key parameter
maxSize = 0.05
minSize = 0.01
fric    = 0.4
kn      = 1e8
emod    = 2e8
kratio  = 2.0
rollingFric = 1.2
adhesiveForce = 0.0
adhesiveRange = 0.0
#==========================

# wall parameter
[wall]
# Size, cube
size = 2
confiningPressure1 = 10000
confiningPressure2 = 50000
confiningPressure3 = 80000
fric = 0.0

[interaction]
fric = 0.0
kn = 100000000


# parameters of Hertz-Mindlin
[servo]
# factory of servo move, the bigger fac, the faster movement.
fac = 0.5


# output options
[output]
logFile = log.txt

